name: Build Obfuscated SO (Docker OLLVM)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/zinclabs/ollvm-clang:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Obfuscated .so
      run: |
        mkdir -p build
        clang++ -mllvm -sub -mllvm -bcf -mllvm -fla -fPIC -shared -o build/liblevelAIann.so levelAIann.cpp

    - name: Upload Obfuscated Artifact
      uses: actions/upload-artifact@v4
      with:
        name: levelAIann-obfuscated
        path: ./build/liblevelAIann.so
