name: Build Shared Library

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compile C++ code to .so
      run: |
        mkdir -p build
        g++ -fPIC -shared -o build/liblevelAIann.so levelAIann.cpp

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: libmylib
        path: build/libmylib.so
